config/routes.rb
# frozen_string_literal: true
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
  root 'users#index', as: 'users'
  devise_for :users
  resources :users, only: %i[show edit destroy update]
end

app/models/application_record.rb
# frozen_string_literal: true
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
# frozen_string_literal: true
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  def online?
    $redis_users_statuses.get(id).present?
  end

  validates :login,
            presence: true,
            uniqueness: {case_sensitive: false},
            length: {minimum: 2, maximum: 25},
            exclusion: {in: %w[Admin Moderator User admin moderator user]}
end

app/controllers/application_controller.rb
# frozen_string_literal: true
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |user|
      user.permit(:email, :login, :password, :password_confirmation)
    end
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  def index
    @users = User.order(:login).page(params[:page])
  end

  def show
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to @user, notice:  t('.user_was_update_successfull')
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to users_url, notice: t('.user_was_destroy_successfull')
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:login)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true
module ApplicationHelper
  def flash_class(level)
    case level
      when 'notice'
        'alert alert-info'
      when 'alert'
        'alert alert-error'
    end
  end
end

app/views/layouts/application.html.slim
doctype html
html lang=I18n.locale.to_s
head
  meta charset='utf-8'
  =stylesheet_link_tag 'application', media: 'all'
  =javascript_include_tag 'application'
  =csrf_meta_tags
body

<!--Навигация -->
/! Navigation

nav.navbar.navbar-inverse.navbar role="navigation"
  .container
    .navbar-header
      button.navbar-toggle data-target="#bs-example-navbar-collapse-1" data-toggle="collapse" type="button"
        span.sr-only =t('.toggle_navigation')
        span.icon-bar
        span.icon-bar
        span.icon-bar
      =link_to t('.name'), users_path, class: 'navbar-brand'
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      ul.nav.navbar-nav
        -if user_signed_in?
          li
           = link_to t('.profile'), user_path(current_user.id)
        -else
          li
           =link_to t('.register_and_auth'), new_user_session_path
.container style="margin-top:70px"
  = render 'layouts/application/flash_messeges'
  .row
    .col-lg-9
      div class="panel panel-default"
        div class="panel-heading"
          h3 class="panel-title" = t '.name'
        div class="panel-body"
          = yield
    .col-md-3
      div class="panel panel-default"
        div class="panel-heading"
          h3 class="panel-title" = t('.adverticement')
        div class="panel-body no_link"
          = t('.adverticement')

app/views/layouts/application/_flash_messeges.html.slim
- flash.each do |key, value|
  div class="#{flash_class(key)} fade in"
    = value
    button type="button" class="close" data-dismiss="alert" aria-hidden="true" &times;

app/views/layouts/email_devise.html.slim
= yield

app/views/layouts/email_devise.text.slim
= yield

app/views/users/edit.html.slim
h1 =t('.edit_profile')

= form_for @user do |f|
    = f.label t('.login')
    br
    = f.text_field :login
    = f.submit t('.rename'), class: 'btn btn-success sign_button'

= link_to t('.show'), user_path(@user.id)
br
= link_to t('.back'), users_path

app/views/users/index.html.slim
h3 =t('.online_users')
table class="table"
  tr class="info"
    td
      = t('.id')
    td
      = t('.login')
    td
      = t('.status')
    td

  -@users.each do |user|
      tr
        td style="width: 1px"
         = user.id
        td
          = user.login
        -if user.online?
          td class="success"
            = t('.online')
        -else
          td class="danger"
            = t('.offline')
        td style="width: 1px"
            = link_to t('.profile'), user_path(user.id)
.pagination_center
  = paginate @users

app/views/users/show.html.slim
div class="page-header"
  h1
    = @user.login
    br
    -if user_signed_in? && current_user.id == @user.id
      small = link_to t('.edit'), edit_user_path(@user)
= link_to t('.on_index'), users_path
-if user_signed_in?
br
    = link_to " #{t('.back')}", destroy_user_session_path, method: :delete